# This workflow will automatically move cards
# in the project board to reflect that status
# of an issue or PR.
name: Update issue cards on project board

on:
  issues:
    types: [opened, labeled, closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PROJECT_URL: https://github.com/orgs/github/projects/2

jobs:
  project_board:
    name: Move cards in the project board according to label
    runs-on: ubuntu-latest
    steps:
      - name: Move to prioritization queue
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: |
          contains(github.event.*.state, 'open') && (
            github.event.action == 'opened' ||
            contains(github.event.*.labels.*.name, 'needs: prioritization')
          )
        env:
          GITHUB_PROJECT_COLUMN_NAME: Needs prioritization
      - name: Move to hold
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: |
          contains(github.event.*.state, 'open') &&
          !contains(github.event.*.labels.*.name, 'needs: prioritization') && (
            contains(github.event.*.labels.*.name, 'blocked') ||
            contains(github.event.*.labels.*.name, 'on hold')
          )
        env:
          GITHUB_PROJECT_COLUMN_NAME: On hold
      - name: Move to completed queue
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: |
          contains(github.event.*.state, 'closed') ||
          github.event.action == 'closed'
        env:
          GITHUB_PROJECT_COLUMN_NAME: Done
